//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://WNG_Sarun_Service", ConfigurationName="INumber")]
public interface INumber
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllNumbers", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllNumbersResponse")]
    long[] GetAllNumbers(long number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllNumbers", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllNumbersResponse")]
    System.Threading.Tasks.Task<long[]> GetAllNumbersAsync(long number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllEvenNumbers", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllEvenNumbersResponse")]
    long[] GetAllEvenNumbers(long number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllEvenNumbers", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllEvenNumbersResponse")]
    System.Threading.Tasks.Task<long[]> GetAllEvenNumbersAsync(long number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllOddNumbers", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllOddNumbersResponse")]
    long[] GetAllOddNumbers(long number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllOddNumbers", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllOddNumbersResponse")]
    System.Threading.Tasks.Task<long[]> GetAllOddNumbersAsync(long number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllNumbersExceptMultiplesOfThreeAndFive", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllNumbersExceptMultiplesOfThreeAndFiveRespon" +
        "se")]
    string[] GetAllNumbersExceptMultiplesOfThreeAndFive(long number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllNumbersExceptMultiplesOfThreeAndFive", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllNumbersExceptMultiplesOfThreeAndFiveRespon" +
        "se")]
    System.Threading.Tasks.Task<string[]> GetAllNumbersExceptMultiplesOfThreeAndFiveAsync(long number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllFibonacciNumbers", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllFibonacciNumbersResponse")]
    long[] GetAllFibonacciNumbers(long number);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WNG_Sarun_Service/INumber/GetAllFibonacciNumbers", ReplyAction="http://WNG_Sarun_Service/INumber/GetAllFibonacciNumbersResponse")]
    System.Threading.Tasks.Task<long[]> GetAllFibonacciNumbersAsync(long number);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INumberChannel : INumber, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NumberClient : System.ServiceModel.ClientBase<INumber>, INumber
{
    
    public NumberClient()
    {
    }
    
    public NumberClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NumberClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NumberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NumberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public long[] GetAllNumbers(long number)
    {
        return base.Channel.GetAllNumbers(number);
    }
    
    public System.Threading.Tasks.Task<long[]> GetAllNumbersAsync(long number)
    {
        return base.Channel.GetAllNumbersAsync(number);
    }
    
    public long[] GetAllEvenNumbers(long number)
    {
        return base.Channel.GetAllEvenNumbers(number);
    }
    
    public System.Threading.Tasks.Task<long[]> GetAllEvenNumbersAsync(long number)
    {
        return base.Channel.GetAllEvenNumbersAsync(number);
    }
    
    public long[] GetAllOddNumbers(long number)
    {
        return base.Channel.GetAllOddNumbers(number);
    }
    
    public System.Threading.Tasks.Task<long[]> GetAllOddNumbersAsync(long number)
    {
        return base.Channel.GetAllOddNumbersAsync(number);
    }
    
    public string[] GetAllNumbersExceptMultiplesOfThreeAndFive(long number)
    {
        return base.Channel.GetAllNumbersExceptMultiplesOfThreeAndFive(number);
    }
    
    public System.Threading.Tasks.Task<string[]> GetAllNumbersExceptMultiplesOfThreeAndFiveAsync(long number)
    {
        return base.Channel.GetAllNumbersExceptMultiplesOfThreeAndFiveAsync(number);
    }
    
    public long[] GetAllFibonacciNumbers(long number)
    {
        return base.Channel.GetAllFibonacciNumbers(number);
    }
    
    public System.Threading.Tasks.Task<long[]> GetAllFibonacciNumbersAsync(long number)
    {
        return base.Channel.GetAllFibonacciNumbersAsync(number);
    }
}
